-- phpMyAdmin SQL Dump
-- version 3.5.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Nov 07, 2012 at 09:55 PM
-- Server version: 5.5.24-log
-- PHP Version: 5.4.3

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `cakecms`
--

-- --------------------------------------------------------

--
-- Table structure for table `series`
--

CREATE TABLE IF NOT EXISTS `series` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `series_name` varchar(100) DEFAULT NULL,
  `html_name` varchar(100) DEFAULT NULL,
  `directory` varchar(100) DEFAULT NULL,
  `sort` int(3) unsigned DEFAULT NULL,
  `overview` text,
  `product_line_overview` text,
  `series_badge` varchar(256) DEFAULT NULL,
  `visible` tinyint(4) DEFAULT '0',
  `meta_title` varchar(250) NOT NULL,
  `meta_description` text NOT NULL,
  `meta_keywords` text NOT NULL,
  `meta_other` text NOT NULL,
  `modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modified_by` varchar(12) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `directory` (`directory`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=19 ;

--
-- Dumping data for table `series`
--

INSERT INTO `series` (`id`, `series_name`, `html_name`, `directory`, `sort`, `overview`, `product_line_overview`, `series_badge`, `visible`, `meta_title`, `meta_description`, `meta_keywords`, `meta_other`, `modified`, `modified_by`) VALUES
(1, 'Mythos', 'Mythos', 'mythos', 10, '<p>\r\n	Mythos Series models are slim, elegant speakers with aircraft grade Aluminum enclosures designed to match the styling of today&rsquo;s high tech flat panel TVs. Mythos loudspeakers are available in space-saving on-wall, shelf-mount and floor-standing configurations for the ultimate in placement flexibility and ease. Their combination of high tech enclosures and drivers along with their narrow shape produce huge, boxless imaging normally found only in ultra high-end speakers. Combine Mythos main, center and surround models with Definitive powered subwoofers for superior performance home theater systems that look as good as they sound.</p>\r\n<p>\r\n	Mythos SuperTower&reg; Series &ndash; Floor-standing SuperTowers offer all the benefits of the Mythos Series loudspeakers along with the awesome benefits of built-in SuperCube&trade; powered subwoofers. With two built-in 300 Watt powered subwoofers you&rsquo;ll enjoy double the bass while saving floor space and enhancing the beauty of your room. Choose between two award-winning Mythos SuperTowers for sonic performance truly in a class by itself.</p>\r\n', '<p>\r\n	Mythos Series models are slim, elegant speakers with aircraft grade Aluminum enclosures designed to match the styling of today&rsquo;s high tech flat panel TVs. Mythos loudspeakers are available in space-saving on-wall, shelf-mount and floor-standing configurations for the ultimate in placement flexibility and ease. Their combination of high tech enclosures and drivers along with their narrow shape produce huge, boxless imaging normally found only in ultra high-end speakers. Combine Mythos main, center and surround models with Definitive powered subwoofers for superior performance home theater systems that look as good as they sound.</p>\r\n', 'mythos.jpg', 1, '', '', '', '', '2012-11-07 23:37:26', 'npalmigiano'),
(2, 'Mythos Sound Bars', 'Mythos Sound Bars', 'mythos-sound-bars', 20, '<p>\r\n	Introducing the perfect solution when rear speakers are not an option&mdash;Definitive&#39;s Mythos SSA range. For everyone who cannot or chooses not to use rear channel speakers but wants all the thrills of five-channel surround sound the Solo Surround Array Series loudspeakers are the optimal choice. The SSA models incorporate Spatial Array a unique patented technology that creates the illusion that you are surrounded by five separate high performance speakers. Enjoying a superb sounding audiophile-grade surround experience has never been more convenient. Simply connect an SSA to any multi-channel receiver and powered subwoofer to enjoy enveloping surround sound without the bother of running long wires and finding places for rear speakers.</p>\r\n', '<p>\r\n	Introducing the perfect solution when rear speakers are not an option&mdash;Definitive&#39;s Mythos SSA range. For everyone who cannot or chooses not to use rear channel speakers but wants all the thrills of five-channel surround sound the Solo Surround Array Series loudspeakers are the optimal choice. The SSA models incorporate Spatial Array a unique patented technology that creates the illusion that you are surrounded by five separate high performance speakers. Enjoying a superb sounding audiophile-grade surround experience has never been more convenient. Simply connect an SSA to any multi-channel receiver and powered subwoofer to enjoy enveloping surround sound without the bother of running long wires and finding places for rear speakers.<br />\r\n	&nbsp;</p>\r\n', 'Sound_bars_alt.jpg', 1, 'Mythos Sound Bars', 'Mythos Sound Bars', '', '', '2012-09-01 15:37:58', 'pdicomo'),
(3, 'Original BP', 'Original BP', 'original-bp', 150, '<p>\r\n	<img alt="" src="/images/userfiles/images/series/BipolarImage.gif" style="width: 175px; height: 250px; margin-right: 10px; margin-left: 10px; float: right; " />Experts agree that bipolar loudspeakers are unquestionably superior for both music and home theater and Definitive is the leader in bipolar technology.</p>\r\n<p>\r\n	Each BP Series speaker incorporates two complete sets of drivers-one facing forward and the other facing to the rear. Definitive&#39;s Bipolar models radiate the full sonic spectrum both forward and rearward in an omni-directional pattern much like sound is produced in real life. The dramatic benefits of Bipolar speakers include a huge three dimensional soundstage for every listener in the room. You don&#39;t have to sit in a confined &#39;sweet spot&#39; to enjoy life-like sound quality. Definitive&#39;s bipolar speakers literally bring your music and movies to life.</p>\r\n<p>\r\n	&nbsp;</p>\r\n', '<p>\r\n	Each BP Series speaker incorporates two complete sets of drivers-one facing forward and the other facing to the rear. Definitive&#39;s Bipolar models radiate the full sonic spectrum both forward and rearward in an omni-directional pattern much like sound is produced in real life. The benefits of Bipolar speakers include a huge three dimensional soundstage for every listener in the room. You don&#39;t have to sit in a confined &acirc;&euro;&oelig;sweet spot&acirc;&euro;? to enjoy life-like sound quality.</p>\r\n', 'BP_orig_150X150.jpg', 1, 'Original BP', 'Original BP', '', '', '2012-09-24 19:02:54', 'npalmigiano'),
(4, 'Studio Monitor', 'Studio Monitor', 'studio-monitor', 40, '<p>\r\n	For applications that demand speakers with compact dimensions but big speaker sound the StudioMonitor bookshelf models are the perfect choice. The StudioMonitors are true full-range speakers with extended low-frequency characteristics, to deliver superb performance both as stand-alone speakers as well as when combined with separate subwoofers.</p>\r\n', '<p>\r\n	For applications that demand speakers with compact dimensions but big speaker sound there is the Studio Monitor series of bookshelf models. The StudioMonitors are true full-range speakers with extended low-frequency characteristics, to deliver superb performance both as stand-alone speakers as well as when combined with separate subwoofers.</p>\r\n', 'bookshelf.jpg', 1, '', '', '', '', '2012-09-01 13:58:15', 'pdicomo'),
(5, 'ProCinema', 'ProCinema', 'procinema', 50, '<p>\r\n	ProCinema/ProMonitor loudspeakers satisfy your need for small, easy-to-place speakers that deliver&nbsp;state-of-the-art, no-compromise performance. ProMonitor satellites are small enough to fit in the palm of your hand and may be wall-mounted, shelf mounted or used on floor-stands making them easy to integrate into any room and d&eacute;cor.</p>\r\n<p>\r\n	ProCinema systems are pre-packaged home theater speaker systems with front, surround, center and subwoofer speaker in one convenient carton. ProMonitor and ProCenter are individually packaged satellite and center speakers that may be mixed and matched with ProSub subwoofers to custom build music and movie systems of astonishing performance capability: The sonic depth, width, and height reproduction and sound of these amazingly compact speakers is so big that Home Theater magazine said they &quot;seem as though they are monster towers if you close your eyes.&quot;</p>\r\n', '<p>\r\n	ProCinema/ProMonitor loudspeakers satisfy your need for small, easy-to-place speakers that deliver state-of-the-art, no-compromise performance. ProMonitor satellites are small enough to fit in the palm of your hand and may be wall-mounted, shelf mounted or used on floor-stands making them easy to integrate into any room and d&eacute;cor.</p>\r\n<p>\r\n	ProCinema systems are pre-packaged home theater speaker systems with front, surround, center and subwoofer speaker in one convenient carton. ProMonitor and ProCenter are individually packaged satellite and center speakers that may be mixed and matched with ProSub subwoofers to custom build music and movie systems of astonishing performance capability: The sonic depth, width, and height reproduction and sound of these amazingly compact speakers is so big that Home Theater magazine said they &quot;seem as though they are monster towers if you close your eyes.&quot;<br />\r\n	&nbsp;</p>\r\n', 'HT_systems_alt.jpg', 1, '', '', '', '', '2012-09-01 15:49:52', 'pdicomo'),
(6, 'BP 8000', 'BP 8000', 'bp8000', 60, '<p>\r\n	The original BP series launched Definitive Technology into becoming the best-selling and most honored brand of audiophile-grade speakers in the US. We&#39;ve improved every part in our award-winning line of Bipolar SuperTowers and matching centers and surrounds in the latest generation BP 8000 series. Forward Focused Bipolar technology, second generation patented BDSS drivers, built-in powered subwoofers, Digital Signal Processing amplifiers, and stunning styling all come together, to set a new standard in performance and value.</p>\r\n<p>\r\n	The new BP family includes four SuperTowers with built-in powered subwoofers for the ultimate in space-saving convenience and heart-pounding performance. There are three perfectly matched centers, two with built-in powered woofers, as well as two bipolar surround speakers to choose from to create a multi-channel system that perfectly meets your needs.</p>\r\n', '<p>\r\n	The BP 8000 series is the newest generation of BP series models and feature our most advanced technologies for better performance than ever.&nbsp;Forward Focused Bipolar technology, second generation patented BDSS drivers, built-in powered subwoofers, Digital Signal Processing amplifiers, and stunning styling come together to set a new standard in performance and value.</p>\r\n<p>\r\n	The new BP family includes four SuperTowers with built-in powered subwoofers for the ultimate in space-saving convenience and heart-pounding performance. There are three perfectly matched centers, two with built-in powered woofers, as well as two bipolar surround speakers to choose from to create a multi-channel system that perfectly meets your needs.</p>\r\n', 'BP8080ST_150X150.jpg', 1, 'BP 8000', 'BP 8000', '', '', '2012-09-01 15:45:00', 'pdicomo'),
(7, 'SuperCube', 'SuperCube', 'supercube', 70, '<p>\r\n	SuperCubes are our best powered subwoofers and dollar for dollar the best powered subwoofers on the market. SuperCube subwoofers are astoundingly compact: the SuperCube&nbsp;2000 is literally not much bigger than a toaster at a mere 10-1/4&quot; cubed. Yet the subterranean bass depth, seismic power and instantaneous quickness of the SuperCubes will bring a level of realism that will remind you of far larger and costlier subwoofers. Professional installers specify SuperCube subwoofers for the finest systems and most demanding applications and listeners.</p>\r\n<p>\r\n	Definitive&#39;s elegant and ultra-compact SuperCube subwoofers deliver ultimate bass performance from beautiful enclosures that fit anywhere. They combine digital amplifiers with DSP,&nbsp;and beefy front-mounted subwoofer drivers&nbsp;which are tightly coupled to dual pressure&nbsp;coupled bass radiators.</p>\r\n', '', 'Subwoofers2.jpg', 1, '', '		', '', '', '2012-09-01 14:26:26', 'pdicomo'),
(8, 'ProSub', 'ProSub', 'prosub', 80, '<p>\r\n	The ProSubs&#39; winning combination of high output, extended and lightening-fast response make them a perfect choice for any audio system. Relentlessly value engineered to bring you top performance at prices that will delight budget-conscious listeners, the ProSub Series is a run-away success story.</p>\r\n<p>\r\n	The ProSub models are high technology active subwoofers with built-in high-power amplifiers and sophisticated electronic crossovers in combination with drivers of the highest quality.The sonic result is accurate, high-impact bass performance, vanishingly low distortion, and high output for the superior home theater sound effects as well as life-like musical excellence.</p>\r\n', '<p>\r\n	This line of compact powered subwoofers was originally conceived to complement the ProMonitor/Pro/Cinema Series but their winning combination of high output, extended and lightening-fast response make them a perfect choice for any audio system. Relentlessly value engineered to bring you top performance at prices that will delight budget-conscious listeners, the ProSub series is a run-away success story.</p>\r\n', 'ProSub_800_150X150.jpg', 1, '', '', '', '', '2012-09-01 14:42:43', 'pdicomo'),
(9, 'UIW In-Wall', 'UIW In-Wall', 'uiw-in-wall', 90, '<p>\r\n	When you want the sound quality of big box speakers but don&#39;t want to use any floor or shelf space, flush mount UIW Series speakers are the perfect solution. Choose from in-ceiling, in-wall and Bipolar surround speakers and even an in-wall subwoofer. These reference-quality loudspeakers deliver superb sound for home or commercial applications.&nbsp;Install Definitive UIW built-in speakers&nbsp;anywhere you want high&nbsp;performance sound.</p>\r\n', '<p>\r\n	When you want the sound quality of big box speakers but don&#39;t want to use any floor or shelf space, flush mount UIW Series speakers are the perfect solution. Choose from in-ceiling, in-wall and Bipolar surround speakers and even an in-wall subwoofer. These reference-quality loudspeakers deliver superb sound for home or commercial applications. Install Definitive UIW built-in speakers anywhere you want high performance sound.<br />\r\n	&nbsp;</p>\r\n', 'UIW-63A_15X150.jpg', 1, 'UIW In-Wall', 'UIW In-Wall', '', '', '2012-09-01 15:18:18', 'pdicomo'),
(10, 'Reference In-Wall', 'Reference In-Wall', 'reference-in-wall', 100, '<p>\r\n	Definitive UIW Reference architectural apeakers are perfect for bringing spectacular-sounding, high-performance &quot;invisible&quot; home theater systems into your home.<br />\r\n	Build a serious &quot;stealth&quot; home theater system by matching any combination of our Reference Series in-wall speakers. Because they use voice-matched components, any combination of Reference models will work well together and deliver superior performance. Pick the ones that best suit your design and listening requirements.</p>\r\n<p>\r\n	The Reference Series of built-in speakers utilize our best technologies and integrated enclosures to deliver the best possible sound quality for ultra-stealth built-in home theater systems. In-wall, in-ceiling, bipolar and in-wall subwoofer speakers are all available to help you create the invisible home theater system of your dreams.</p>\r\n', '<p>\r\n	The Reference Series of built-in speakers utilize our best technologies and integrated enclosures to deliver the best possible sound quality for ultra-stealth built-in home theater systems. In-wall, in-ceiling, bipolar and in-wall subwoofer speakers are all available to help you create the invisible home theater system of your dreams.</p>\r\n', 'RCS_150X150.jpg', 1, 'Reference In-Wall', 'Reference In-Wall', '', '', '2012-09-01 14:56:03', 'pdicomo'),
(11, 'All Weather', 'All Weather', 'all-weather', 120, '<p>\r\n	Now you can enjoy the incomparable sound of Definitive Technology anywhere around your home with the groundbreaking AW5500 and AW6500 All-Weather loudspeakers. With their fully sealed design, aluminum grilles, and rugged PolyStone enclosures, the AWs can be fully exposed to the elements and reliably deliver their indoor speaker sound quality for years of outdoor listening enjoyment. Their high technology components and unique design deliver clear mids, extended highs, and thunderous bass even in the tough acoustic conditions of the outdoors. Now you can have it all &mdash; great Definitive sound on the patio, deck, garden or in the sauna.</p>\r\n', '<p>\r\n	Now you can enjoy the incomparable sound of Definitive Technology anywhere around your home with the groundbreaking AW5500 and AW6500 All-Weather loudspeakers. With their fully sealed design, aluminum grilles, and rugged PolyStone enclosures, the AWs can be fully exposed to the elements and reliably deliver their indoor speaker sound quality for years of outdoor listening enjoyment. Their high technology components and unique design deliver clear mids, extended highs, and thunderous bass even in the tough acoustic conditions of the outdoors. Now you can have it all &mdash; great Definitive sound on the patio, deck, garden or in the sauna.<br />\r\n	&nbsp;</p>\r\n', 'Outdoor_alt.jpg', 1, '', '', '', '', '2012-09-01 15:50:44', 'pdicomo'),
(12, 'Disappearing In-Wall', 'Disappearing In-Wall', 'disappearing-in-wall', 110, '<p>\r\n	You want great sound everywhere in your home, but you may not always have room for or want the visual intrusion of free-standing speakers. Definitive&#39;s Disappearing <sup>(TM)</sup>&nbsp;In-Wall series speakers feature near-invisibility thanks to their small area, hidden flange design, and low profile micro-perf grilles. They are as easy to install as traditional flanged flush-mount speakers, and don&#39;t require custom sheetrock/spackle skills to install yet they are practically invisible.</p>\r\n', '<p>\r\n	You want great sound everywhere in your home, but you may not always have room for or want the visual intrusion of free-standing speakers. Definitive&#39;s Disappearing (TM) In-Wall series speakers feature near-invisibility thanks to their small area, hidden flange design, and low profile micro-perf grilles. They are as easy to install as traditional flanged flush-mount speakers, and don&#39;t require custom sheetrock/spackle skills to install yet they are practically invisible.<br />\r\n	&nbsp;</p>\r\n', 'Inwall.jpg', 1, '', '', '', '', '2012-09-01 15:28:11', 'pdicomo'),
(13, 'C/L/R', 'C/L/R', 'c-l-r', 130, '<p>\r\n	As well as being the matching center channel models for Bipolar Series floor-standing and Studio Monitor bookshelf speakers, the C/L/R models are outstanding speakers for main left &amp; right and surround applications. All C/L/R models are magnetically shielded for safe placement next to CRT-style (tube) TVs. Three of the four C/L/R models feature built-in powered subwoofers for stunningly powerful performance.</p>\r\n<p>\r\n	Definitive has always led the industry with the best-sounding shielded center channels available. Optimum surround sound home theater reproduction places heavy demands on the center channel speaker, which in many respects is the main speaker in the system and often handles 50% or more of the program material. It is no place to compromise and settle for second best. Because of this, Definitive pioneered the concept of full frequency range high-definition center-channel speakers. Definitive&#39;s center channels and C/L/Rs are consistently rated as the best available, and have won numerous Audio Video Grand Prix Center Channel of the Year Awards.</p>\r\n', '<p>\r\n	As well as being the matching center channel models for Bipolar Series floor-standing and Studio Monitor bookshelf speakers, the C/L/R models are outstanding speakers for main left &amp; right and surround applications. Three of the four C/L/R models feature built-in powered subwoofers for stunningly powerful performance.</p>\r\n', '', 0, '', '', '', '', '2012-09-01 13:54:48', 'pdicomo'),
(14, 'Mythos XTR', 'Mythos XTR', 'mythos-xtr', 30, '<p>\r\n	The Mythos XTR series models are ultra-slim on-wall/on-shelf high performance loudspeakers designed to match today&#39;s super shallow TVs. The award winning Mythos XTR-50 was the&nbsp;first ultra-shallow (only 1.5&quot; deep) high performance speaker to enter&nbsp;the market. It&#39;s patent pending technologies and premium materials&nbsp;yielded sound performance that equaled or exceeded full-depth on-wall speakers. Now there are&nbsp;four XTR series models to answer any application need, including a dedicated surround channel speaker.</p>\r\n', '<p>\r\n	The Mythos XTR series models are ultra-slim on-wall/on-shelf high performance loudspeakers designed to match today&#39;s super shallow TVs. The award winning Mythos XTR-50 was the first ultra-shallow (only 1.5&quot; deep) high performance speaker to enter the market. It&#39;s patent pending technologies and premium materials yielded sound performance that equaled or exceeded full-depth on-wall speakers. Now there are four XTR series models to answer any application need, including a dedicated surround channel speaker.<br />\r\n	&nbsp;</p>\r\n', 'onwall_alt.jpg', 1, 'Mythos XTR', 'Mythos XTR', '', '', '2012-09-01 15:37:33', 'pdicomo');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
